name: Consul-monitor Linux debug build

on:
  push:
    branches:
      - "!master"
  pull_request:
    branches:
      - "!master"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build dev
      run: cargo build --debug --verbose
    - name: Run tests
      run: cargo test --debug --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: consul-monitor-bin
        path: target/debug/consul-monitor*
        if-no-files-found: error
