name: Consul-monitor Linux release build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: consul-monitor-bin
        path: target/release/consul-monitor*
        if-no-files-found: error
